express:
  port: 3000

logger:
  init:
    level: info
  http:
    level: trace

knex-mysql:
  connection:
    host: '127.0.0.1'
    user: 'root'
    password: ''
    database: 'test'

express-session-redis:
  cookie:
    maxAge: 3600000

mysql:
  host: '127.0.0.1'
  user: 'root'
  password: ''
  database: 'test'
